//created on: Jul 23, 2015
package com.sample

rule "Rule 1"

    when
        $c:Company(companyId == 123)
    then
        System.out.println("Company Id and Company Name is ---> " + $c.getCompanyId() + " , " + $c.getCompanyName() ) ;

end

rule "Rule 2"
    when
    	$c:Company(companyId == 12345)
    then
		System.out.println("Company Id and Company Name is ---> " + $c.getCompanyId() + " , " + $c.getCompanyName() ) ;
end
